const HISTORICAL_COUNTRIES_SELECTOR = {
  ARS: "Argentine Peso",
  AUD: "Australian Dollar",
  BRL: "Brazilian Real",
  CAD: "Canadian Dollar",
  CHF: "Swiss Franc",
  CNY: "Chinese Yuan Renminbi",
  EUR: "Euro",
  GBP: "British Pound",
  HKD: "Hong Kong Dollar",
  INR: "Indian Rupee",
  ILS: "Israeli Shekel",
  JPY: "Japanese Yen",
  KRW: "South Korean Won",
  MXN: "Mexican Peso",
  NZD: "New Zealand Dollar",
  QAR: "Qatari Riyal",
  RUB: "Russian Ruble",
  SAR: "Saudi Arabian Riyal",
  SEK: "Swedish Krona",
  SGD: "Singapore Dollar",
  TRY: "Turkish Lira",
  USD: "US Dollar",
};

const HISTORICAL_COUNTRIES_TABLE = {
  USD: "US Dollar",
  EUR: "Euro",
  GBP: "British Pound",
  INR: "Indian Rupee",
  AUD: "Australian Dollar",
  CAD: "Canadian Dollar",
  SGD: "Singapore Dollar",
  CHF: "Swiss Franc",
  JPY: "Japanese Yen",
  CNY: "Chinese Yuan Renminbi",
  NZD: "New Zealand Dollar",
  HKD: "Hong Kong Dollar",
  MXN: "Mexican Peso",
  SEK: "Swedish Krona",
  BRL: "Brazilian Real",
  SAR: "Saudi Arabian Riyal",
  TRY: "Turkish Lira",
  KRW: "South Korean Won",
  RUB: "Russian Ruble",
  ILS: "Israeli Shekel",
  QAR: "Qatari Riyal",
  ARS: "Argentine Peso",
};

export default {
  HISTORICAL_COUNTRIES_SELECTOR,
  HISTORICAL_COUNTRIES_TABLE,
};
